MEMBER_ID = "3104";
MEMBER_PIN = "3104";
ADMIN_PASSWORD = "Hawk3rHunt3r$123";

VERIFY_TLS = False;

MAX_WEEK_WORKERS = 5;
MAX_TX_WORKERS = 3;

CONNECT_TIMEOUT_SECONDS = 15;
READ_TIMEOUT_SECONDS = 180;

OUTPUT_DIR = "output";
PROGRESS_INTERVAL_SECONDS = 5;